services:
  app_backend:
    build: .
    container_name: app_backend
    command: ["api"]
    ports:
      - "8006:8000"
    depends_on:
      - redis_app_backend
      - postgres_app_backend
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    restart: always # options are? no, always, on-failure, unless-stopped
    # Resource constraints (compose, non-Swarm)
    mem_limit: 2048m # Maximum memory usage is 2gb
    cpus: 1 # Limit to 100% of a single CPU core
    pids_limit: 256 # Limit to 256 processes/threads
    oom_kill_disable: false
    logging: # Log configuration can be found here: https://docs.docker.com/config/containers/logging/configure/
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./app/:/raiz/app

  worker_app_backend:
    build: .
    env_file:
      - .env
    container_name: celery_app_backend_worker
    command: ["worker"]
    depends_on:
      - redis_app_backend

  beat_app_backend:
    build: .
    env_file:
      - .env
    container_name: celery_app_backend_beat
    command: ["beat"]
    depends_on:
      - redis_app_backend

  flower_app_backend:
    build: .
    env_file:
      - .env
    container_name: celery_app_backend_flower
    command: ["flower"]
    ports:
      - "5596:5555"
    depends_on:
      - redis_app_backend

  redis_app_backend:
    image: redis
    container_name: redis_app_backend
    restart: always
    ports:
      - "6398:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_app_backend_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  postgres_app_backend:
    image: postgres:16-alpine
    container_name: postgres_app_backend
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d dbname"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_app_backend_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  postgres_app_backend_data:
  redis_app_backend_data:
